streetviewInterface/mySite/ImagePicker/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^index_figures/$', views.index_figures, name='index_figures'),
    url(r'^post_zoning/$', views.post_zoning, name='post_zoning'),

    url(r'^routePicker/$', views.routePicker, name='routePicker'),
    url(r'^crawler/$', views.crawler, name='crawler'),
    url(r'^bfs/$', views.bfs, name='bfs'),
    url(r'^get_current_bfs_queue_item/$', views.get_current_bfs_queue_item, name='get_current_bfs_queue_item'),
    url(r'^initialize_bfs/$', views.initialize_bfs, name='initialize_bfs'),
    url(r'^savePoint/$', views.savePoint, name='savePoint'),
    url(r'^listImage/(?P<streetviewImage_pk>[0-9]+)/$',  views.listImage, name='listImage'), #
    url(r'^listImage_AIN/(?P<streetviewImage_pk>[0-9]+)/$',  views.listImage_AIN, name='listImage_AIN'), #

    url(r'^listImages/$',  views.listImages, name='listImages'), #

    url(r'^read_mapPoint/$',  views.read_mapPoint, name='read_mapPoint'), #

    url(r'^list_CTPN_metadata/$',  views.list_CTPN_metadata, name='list_CTPN_metadata'), #
    url(r'^list_crnn_metadata/$',  views.list_crnn_metadata, name='list_crnn_metadata'), #
    url(r'^list_ECN_metadata/$',  views.list_ECN_metadata, name='list_ECN_metadata'), #
    url(r'^metadata_zoning/$', views.metadata_zoning, name='metadata_zoning'),


    url(r'^listBoundingBox/$',  views.listBoundingBox, name='listBoundingBox'), #
    url(r'^postBoundingBox/$',  views.postBoundingBox, name='postBoundingBox'),
    url(r'^postOCR/$',  views.postOCR, name='postOCR'), #

    url(r'^image_saver_metadata/$',  views.image_saver_metadata, name='image_saver_metadata'), #
    url(r'^set_image_pending/$',  views.set_image_pending, name='set_image_pending'), #
    url(r'^set_image_uploaded/$',  views.set_image_uploaded, name='set_image_uploaded'), #
    url(r'^deletePending/$',  views.deletePending, name='deletePending'), #


    url(r'^picker/$', views.picker, name='picker'),

    url(r'^deleteAllBoundingBox/$',  views.deleteAllBoundingBox, name='deleteAllBoundingBox'), #
    url(r'^deleteAllStreetviewImages/$',  views.deleteAllStreetviewImages, name='deleteAllStreetviewImages'), #
    url(r'^deleteDuplicateMapPoints/$',  views.deleteDuplicateMapPoints, name='deleteDuplicateMapPoints'), #
    url(r'^runGoogleOCR_images/$',  views.runGoogleOCR_images, name='runGoogleOCR_images'), #
    url(r'^runGoogleOCR_boundingBoxes/$',  views.runGoogleOCR_boundingBoxes, name='runGoogleOCR_boundingBoxes'), #

    url(r'^deleteAllOcr/$',  views.deleteAllOcr, name='deleteAllOcr'), #

    url(r'^deleteAllMapPoints/$',  views.deleteAllMapPoints, name='deleteAllMapPoints'), #
    url(r'^adminPanel/$',  views.adminPanel, name='adminPanel'), #
    url(r'^deleteStreetviewImage/(?P<streetviewImage_pk>[0-9]+)/$',  views.deleteStreetviewImage, name='deleteStreetviewImage'), #
    url(r'^boundingBox/(?P<boundingBox_pk>[0-9]+)/$',  views.boundingBox, name='boundingBox'), #
    url(r'^boundingBox_expanded/(?P<boundingBox_pk>[0-9]+)/$',  views.boundingBox_expanded, name='boundingBox_expanded'), #


    url(r'^overlayBox/(?P<image_pk>[0-9]+)/(?P<x1>[0-9]+)/(?P<x2>[0-9]+)/(?P<y1>[0-9]+)/(?P<y2>[0-9]+)/$',  views.overlayBox, name='overlayBox'), #

    url(r'^AIN_to_image/(?P<AIN>[0-9]+)/$',  views.AIN_to_image, name='AIN_to_image'), #


    url(r'^runGoogleOCR_image/(?P<pk>[0-9]+)/$',  views.runGoogleOCR_image, name='runGoogleOCR_image'), #


    url(r'^runGoogleOCR_randomImage/$',  views.runGoogleOCR_randomImage, name='runGoogleOCR_randomImage'), #

    url(r'^runGoogleOCR_boundingBox/(?P<boundingBox_pk>[0-9]+)/$',  views.runGoogleOCR_boundingBox, name='runGoogleOCR_boundingBox'), #
    url(r'^deleteOcrText/(?P<ocrtext_pk>[0-9]+)/$',  views.deleteOcrText, name='deleteOcrText'), #
    url(r'^deleteBoundingBox/(?P<pk>[0-9]+)/$',  views.deleteBoundingBox, name='deleteBoundingBox'), #

    url(r'^benchmarkingPanel/$',  views.benchmarkingPanel, name='benchmarkingPanel'), #
    url(r'^annotateRandomBoundingBox/$',  views.annotateRandomBoundingBox, name='annotateRandomBoundingBox'), #
    url(r'^postManualOCR/$',  views.postManualOCR, name='postManualOCR'), #
    url(r'^runGoogleOCR_manualOCR/$',  views.runGoogleOCR_manualOCR, name='runGoogleOCR_manualOCR'), #

    url(r'^runLanguageIdentifiction/$',  views.runLanguageIdentifiction, name='runLanguageIdentifiction'), #
    url(r'^deleteAllOcrLanguage/$',  views.deleteAllOcrLanguage, name='deleteAllOcrLanguage'), #
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production

streetviewInterface/mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')), # for description, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('myContent.urls', namespace='myContent')),
    url(r'^ImagePicker/', include('ImagePicker.urls', namespace='ImagePicker')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production

streetviewInterface/mySite/ImagePicker/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
import os
import urllib.request
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import ast
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from math import sqrt
from collections import Counter, defaultdict
from .google_ocr import *
import time
import sys
import subprocess
from random import randint
import json
import csv
from .views_saveImage import *
from .views_figures import *
from .views_interface import *
from django.http import JsonResponse
from io import BytesIO
from django.db.models import Count


def AIN_to_image(request, AIN):
    signs = Sign.objects.filter(AIN=AIN)
    streetviewImages = signs.values_list('streetviewImage__pk',flat=True).distinct()
    streetviewImages = StreetviewImage.objects.filter(pk__in=streetviewImages).order_by('-pk')
    context = {'streetviewImages':streetviewImages,'AIN':AIN}
    return render(request, 'ImagePicker/AIN_to_image.html',context)

def overlayBox(request,image_pk,x1,x2,y1,y2):
    width = int(x2)-int(x1)
    height = int(y2)-int(y1)
    streetviewImage = StreetviewImage.objects.get(pk=image_pk)
    context = {'streetviewImage':streetviewImage,'x1':x1,'y1':y1,'width':width,'height':height}
    return render(request, 'ImagePicker/overlayBoundingBox.html',context)







def deletePending(request):
    if not request.user.is_superuser:
        return HttpResponse("you are not an admin")
    Pending.objects.all().delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def boundingBox(request,boundingBox_pk):
    boundingBox = BoundingBox.objects.get(pk=boundingBox_pk)
    if boundingBox.is_nil == True:
        return HttpResponse("nil bounding box")
    image_url = boundingBox.streetviewImage.image_url()
    response = requests.get(image_url)
    img = Image.open(BytesIO(response.content))
    img = img.crop((boundingBox.x1, boundingBox.y1, boundingBox.x2, boundingBox.y2 ))
    response = HttpResponse(content_type="image/jpeg")
    img.save(response, "JPEG")
    return response

def boundingBox_expanded(request,boundingBox_pk):
    boundingBox = BoundingBox.objects.get(pk=boundingBox_pk)
    image_url = os.path.join(settings.MEDIA_ROOT,boundingBox.streetviewImage.image.name)
    img = Image.open(os.path.join(image_url))
    img = img.crop((boundingBox.x1_expanded(), boundingBox.y1_expanded(), boundingBox.x2_expanded(), boundingBox.y2_expanded() ))
    response = HttpResponse(content_type="image/jpeg")
    img.save(response, "JPEG")
    return response

def listImage(request,streetviewImage_pk):
    streetviewImage = StreetviewImage.objects.get(pk=streetviewImage_pk)
    context = {'streetviewImage':streetviewImage}
    return render(request, 'ImagePicker/listImage.html',context)

def listImage_AIN(request,streetviewImage_pk):
    streetviewImage = StreetviewImage.objects.get(pk=streetviewImage_pk)
    context = {'streetviewImage':streetviewImage}
    return render(request, 'ImagePicker/listImage_AIN.html',context)



def listImages(request):
    streetviewImages = StreetviewImage.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(streetviewImages, 10)
    try:
        streetviewImages_page = paginator.page(page)
    except PageNotAnInteger:
        streetviewImages_page = paginator.page(1)
    except EmptyPage:
        streetviewImages_page = paginator.page(paginator.num_pages)

    context = {'streetviewImages':streetviewImages_page}
    return render(request, 'ImagePicker/listImages.html',context)

# Takes POST data
# saves mapPoint
# downloads associated streetview images to point and saves streetviewImage (2 per mapPoint for right and left)
def savePoint(request):
    if request.method != 'POST':
        return HttpResponse("Must be POST")

    latitude = float(request.POST.get("latitude"))
    longitude = float(request.POST.get("longitude"))
    panoID = str(request.POST.get("panoID"))
    mapPointTag_str = str(request.POST.get("mapPointTag"))
    photographerHeading = float(request.POST.get("photographerHeading"))
    mapPoint = MapPoint(latitude=latitude, \
                        longitude=longitude, \
                        panoID=panoID, \
                        photographerHeading=photographerHeading, \
                        tag = mapPointTag_str)
    mapPoint.save()
    time.sleep(0.5)
    return HttpResponse("done")

# See: https://www.fcc.gov/general/census-block-conversions-api
def get_census_tracts():
    mapPoints = MapPoint.objects.filter(censusblock__isnull=True)
    url_template = 'http://data.fcc.gov/api/block/%d/find?format=json&latitude=%f&longitude=%f&showall=true'
    for mapPoint in mapPoints:
        url = url_template % (2010,mapPoint.latitude,mapPoint.longitude)
        with urllib.request.urlopen(url) as url:
            data = json.loads(url.read().decode())
        # figure out whether intersection or single tract
        if 'intersection' in data['Block'].keys(): # if true, then we have intersection
            for el in data['Block']['intersection']:
                fips = el['FIPS']
                censusBlock = CensusBlock(mapPoint = mapPoint, fips = fips)
                censusBlock.save()
                print(censusBlock)
        else:
            fips = data['Block']['FIPS']
            censusBlock = CensusBlock(mapPoint = mapPoint, fips = fips)
            censusBlock.save()
            print(censusBlock)

def dumpDB(name,obj):
    with open('media/' + name, 'w') as csvfile:
        fieldnames = ['pk', 'latitude', 'longitude']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames, delimiter='\t')
        writer.writeheader()
        print("starting dump of " + name)
        pks = obj.objects.values_list('pk',flat=True)
        for pk in pks:
            row = obj.objects.get(pk=pk)
            writer.writerow({'pk':                  row.pk, \
                             'latitude':            row.latitude_val(), \
                             'longitude':           row.longitude_val(), \
                            })




def read_mapPoint(request):
    with open('output/MapPoints.csv', 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            pk                   = int(row[0])
            latitude             = float(row[1])
            longitude            = float(row[2])
            photographerHeading  = float(row[3])
            panoID               = str(row[4])
            tag                  = str(row[5])
            mapPoint = MapPoint(latitude=latitude, \
                                longitude=longitude, \
                                photographerHeading=photographerHeading, \
                                panoID=panoID, \
                                tag=tag, \
                                )
            mapPoint.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def listBoundingBox(request): # TODO: make urls to cropped image
    if request.method == 'POST':
        if not request.user.is_superuser:
            return HttpResponse("you are not an admin")
        cmd = request.POST.get("command")
        boundingBoxes = eval(cmd)
    else:
        boundingBoxes = BoundingBox.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(boundingBoxes, 10)
    try:
        boundingBoxes_page = paginator.page(page)
    except PageNotAnInteger:
        boundingBoxes_page = paginator.page(1)
    except EmptyPage:
        boundingBoxes_page = paginator.page(paginator.num_pages)

    context = {'boundingBoxes':boundingBoxes_page,'total_number':len(boundingBoxes),'num_images':len(StreetviewImage.objects.filter(boundingbox__in=boundingBoxes).distinct())}

    return render(request, 'ImagePicker/listBoundingBox.html',context)




def deleteAllOcr(request):
    if not request.user.is_superuser:
        return HttpResponse("you are not an admin")
    OcrText.objects.all().delete()
    return HttpResponseRedirect(reverse('ImagePicker:adminPanel'))

def deleteAllBoundingBox(request):
    if not request.user.is_superuser:
        return HttpResponse("you are not an admin")
    BoundingBox.objects.all().delete()
    return HttpResponseRedirect(reverse('ImagePicker:adminPanel'))

def deleteAllStreetviewImages(request):
    if not request.user.is_superuser:
        return HttpResponse("you are not an admin")
    StreetviewImage.objects.all().delete()
    return HttpResponseRedirect(reverse('ImagePicker:adminPanel'))

def deleteStreetviewImage(request,streetviewImage_pk):
    if not request.user.is_superuser:
        return HttpResponse("you are not an admin")
    streetviewImage = StreetviewImage.objects.get(pk=streetviewImage_pk)
    streetviewImage.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def deleteBoundingBox(request,pk):
    if not request.user.is_superuser:
        return HttpResponse("you are not an admin")
    boundingBox = BoundingBox.objects.get(pk=pk)
    boundingBox.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def deleteAllMapPoints(request):
    if not request.user.is_superuser:
        return HttpResponse("you are not an admin")
    MapPoint.objects.all().delete()
    return HttpResponseRedirect(reverse('ImagePicker:adminPanel'))

def adminPanel(request):
    context = {}
    return render(request, 'ImagePicker/adminPanel.html',context)

def benchmarkingPanel(request):
    num_benchmarked = len(BoundingBox.objects.filter( ocrtext__method__contains = "manual"))
    total = len(BoundingBox.objects.all())

    columns =   ['english','spanish','chinese','japanese'          ,'korean'   ,'thai'    ,'other']
    locations = ['woodman','pico'   ,'garvey' ,'tokyo(NONEXISTANT)','koreatown','thaitown','other(NONEXISTANT)']

streetviewInterface/mySite/ImagePicker/templates/ImagePicker/adminPanel.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
<style>

</style>

{% endblock %}

{% block title %}
  List
{% endblock %}

{% block body_block %}
  <div class="content">


    <h1>{{ message }}</h1>

    <h2>Admin panel</h2>
    <h1>{{ message }}</h1>

    <hr>
    <hr>
    <h1>{{ message }}</h1>

    <h2>Useful</h2>
    <a href="{% url 'ImagePicker:deleteDuplicateMapPoints' %}">Delete duplicate map points</a>    <br />
    <a href="{% url 'ImagePicker:saveImages' %}">Save images from MapPoints</a>    <br />
    <!--<a href="{% url 'ImagePicker:runGoogleOCR_images' %}">Run google bounding box, ocr on 500 images</a>    <br />-->
    <!--<a href="{% url 'ImagePicker:runGoogleOCR_boundingBoxes' %}">Run google ocr on bounding boxes</a>    <br /> -->
    <a href="{% url 'ImagePicker:runGoogleOCR_randomImage' %}">Run googleOCR on a single random image</a>    <br />
    <a href="{% url 'ImagePicker:runLanguageIdentifiction' %}">Run dictionary-based language identification</a>    <br />

    <p>~~~~~~~~~</p>

    <h2>Interface to CTPN, crnn</h2>
    <a href="{% url 'ImagePicker:list_CTPN_metadata' %}">Image metadata for CTPN</a>  <br />
    <a href="{% url 'ImagePicker:list_crnn_metadata' %}">Bounding box metadata for crnn</a> <br />
    <a href="{% url 'ImagePicker:list_ECN_metadata' %}">Bounding box metadata for ECN script identification</a> <br />

    <p>~~~~~~~~~</p>
    <h2>Delete data. CAREFUL</h2>
    <a href="{% url 'ImagePicker:deleteAllMapPoints' %}">Delete all map points</a>  <br />
    <a href="{% url 'ImagePicker:deleteAllStreetviewImages' %}">Delete all images</a><br />
    <a href="{% url 'ImagePicker:deleteAllBoundingBox' %}">Delete all bounding boxes</a><br />
    <a href="{% url 'ImagePicker:deleteAllOcr' %}">Delete all OCR text</a>  <br />
    <a href="{% url 'ImagePicker:deleteAllOcrLanguage' %}">Delete all language detections</a>  <br />
    <a href="{% url 'ImagePicker:initialize_bfs' %}">Delete crawler queue</a><br />
    <a href="{% url 'ImagePicker:read_mapPoint' %}">read mapPoint in</a>  <br />

    <p>~~~~~~~~~</p>
    <h2>Manager</h2>
    <a href="{% url 'ImagePicker:deletePending' %}">Delete pending tasks</a>  <br />


  </div>
{% endblock %}

streetviewInterface/mySite/ImagePicker/templates/ImagePicker/annotateRandomBoundingBox.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
<style>

.mc-image-container {
  min-width: 300px;
  max-width: 400px;
  overflow: auto;
}

.outline {
  border: 1px solid black;
  display: inline-block;
}

.outline p {
  margin-top: 10px;
  margin-left: 10px;
  margin-right: 10px;
}

</style>

{% endblock %}

{% block title %}
  List
{% endblock %}

{% block body_block %}
  <div class="content">

    <div>
      <a href="/{{ boundingBox.streetviewImage.image.url }}">
        <img src="/ImagePicker/boundingBox/{{ boundingBox.pk }}/">
      </a>
    </div>

    <br />
    <br />

    <div class="outline">
      <form action="{% url 'ImagePicker:postManualOCR' %}" method="POST">
        {% csrf_token %}
        text &nbsp; &nbsp; = <input type="text" name="text" size=20><br />
        locale = <input id="marker_tag" type="text" name="locale" size=20><br />
        notes &nbsp; &nbsp; = <input type="text" name="notes" size=20><br />
        <input type="hidden" name="pk" value="{{ boundingBox.pk }}"><br />
        <input type="submit" value="Submit"><br />
      </form>
    </div>

    <h3>Expanded image</h3>
    <div>
      <a href="/{{ boundingBox.streetviewImage.image.url }}">
        <img src="/ImagePicker/boundingBox_expanded/{{ boundingBox.pk }}/">
      </a>
    </div>

    <h3>Notes</h3>
    Notes:
    traffic_sign
    false_positive
    unreadable
    numbers
    truncated
    watermark


    <br />~~~~~~~~~~~<br />
    <a href="{% url 'ImagePicker:deleteBoundingBox' pk=boundingBox.pk %}">Delete (CAREFUL!!)</a><br />


  </div>
{% endblock %}

streetviewInterface/mySite/ImagePicker/templates/ImagePicker/index.html
<!-- see: https://developers.google.com/maps/documentation/javascript/examples/streetview-events -->



{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}

  <style>
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    #pano, #pano1, #pano2 {
      width: 100%;
      height: 100%;
    }
    #map {
      width: 100%;
      height: 100%;
    }
  </style>


  <script>
  </script>


{% endblock %}

{% block title %}
  index
{% endblock %}

{% block body_block %}

  <h1>Statistics</h1>
  {{ mapPoints }} total MapPoints <br />
  {{ mapPoints_withTags }} MapPoints with zone code <br />
  {{ mapPoints_withTract}} MapPoints with census tracts <br />
  {{ streetviewImages }} images saved <br />
  {{ pending }} pending <br />





  <p>~~~~~~~~~~~~~</p>
  {{ mapPoints }} total MapPoints
  <li>{{ numDuplicate_mapPoints }} duplicates. <a href="{% url 'ImagePicker:deleteDuplicateMapPoints' %}">Delete duplicates</a></li>

  <p>~~~~~~~~~~~~~</p>

  {{ streetviewImages }} images saved
  <li>{{ streetviewImages_withBB }} have bounding boxes.</li>


  <p>~~~~~~~~~~~~~</p>
  {{ boundingBoxes }} total bounding boxes (this includes dummy bounding boxes generated for images with no text detected)
  <li>{{ boundingBoxes_no_google_text }} bounding boxes have no google ocr text.</li>
  <li>{{ boundingBoxes_no_crnn_text }} bounding boxes have no crnn text.</li>

  <p>~~~~~~~~~~~~~</p>
  {{ googleOCR }} OCR results<br />
  Number tracts: {{ FIPS }} <br />
  {{ language_count }}


{% endblock %}

streetviewInterface/mySite/ImagePicker/templates/ImagePicker/listBoundingBox.html
{% extends "MCBase/base-extended.html" %}
{% load staticfiles %}

{% block javascript %}
<style>

table, th, td {
    border: 1px solid black;
    padding: 10px;
}

.mc-image-container {
  min-width: 300px;
  max-width: 400px;
  overflow: auto;
}

.outline {
  border: 1px solid black;
  display: inline-block;
}

.outline p {
  margin-top: 10px;
  margin-left: 10px;
  margin-right: 10px;
}

</style>

{% endblock %}

{% block title %}
  List
{% endblock %}

{% block body_block %}
  <div class="content">
    <h1>List of all bounding boxes</h1>

    <div class="outline">
      <p>
        total # bounding boxes = {{ total_number }} <br />
        total # of images = {{ num_images }}
      </p>
    </div>

    <br />
    <br />

    <!-- filter -->
    <div class="outline">
      <form action="{% url 'ImagePicker:listBoundingBox' %}" method="POST">
        {% csrf_token %}
        boundingBoxes =
        <input type="text" name="command" size=100><br />
        <input type="submit" value="Submit"><br />
        Examples: <br />
        BoundingBox.objects.exclude(ocrtext__isnull=True)<br />
        BoundingBox.objects.filter(ocrtext__method__contains="google",ocrtext__locale__contains="locale=ko")<br />
        BoundingBox.objects.filter(ocrtext__method__contains="manual")<br />
        BoundingBox.objects.filter(streetviewImage__mapPoint__tag="thaitown")<br />
        BoundingBox.objects.filter(method="google").filter(streetviewImage__mapPoint__tag="garvey").filter(ocrtext__method="manual",ocrtext__locale="spanish")
      </form>
    </div>

    <br />
    <br />


    <table>
      {% for boundingBox in boundingBoxes %}

      <tr>

          <!-- image -->
          <td>
            <div class="mc-image-container">
                <img src="/ImagePicker/boundingBox/{{ boundingBox.pk }}/">
            </div>
          </td>

          <!-- info -->
          <td>
            <div class="mc-image-container">
              bounding box pk: {{ boundingBox.pk }} <br />
              bounding box method: {{ boundingBox.method }}
              <br />
              original image: <a href="/{{ boundingBox.streetviewImage.image.url }}">{{ boundingBox.streetviewImage.image.name }}</a>
              <br />
              x1= {{ boundingBox.x1 }}, x2= {{ boundingBox.x2 }}, y1={{ boundingBox.y1 }}, x2={{ boundingBox.y2 }} <br />
              <a href="{% url 'ImagePicker:deleteBoundingBox' pk=boundingBox.pk %}">Delete (CAREFUL!!)</a><br />
              tag: {{ boundingBox.streetviewImage.mapPoint.tag }}<br />
            </div>
          </td>

          {% for ocrText in boundingBox.ocrtext_set.all|dictsort:"method" %}
	   <td>
              <div class="mc-image-container">
                method: {{ ocrText.method }}<br />
                text: {{ ocrText.text }}<br />
                locale: {{ ocrText.locale }}<br />
                score: {{ ocrText.score }}<br />
                notes: {{ ocrText.notes }}<br />
                languageIdentification: {{ ocrText.ocrlanguage_set.all.0.language }}<br />
                 {{ ocrText.ocrlanguage_set.all.0.notes }}<br />
                <a href="{% url 'ImagePicker:deleteOcrText' ocrtext_pk=ocrText.pk %}">delete</a>
              </div>
            </td>
          {% endfor %}

          {% if not boundingBox.googleOCR %}
          <td>
            <div class="mc-image-container">
                <a href="{% url 'ImagePicker:runGoogleOCR_boundingBox' boundingBox_pk=boundingBox.pk %}">run google ocr</a>
            </div>
          </td>
         {% endif %}

         {% if not boundingBox.manualAnnotation %}
         <td>
           <div class="mc-image-container">
             <form action="{% url 'ImagePicker:postManualOCR' %}" method="POST">
               {% csrf_token %}
               text &nbsp; &nbsp; = <input type="text" name="text" size=20><br />
               locale = <input id="marker_tag" type="text" name="locale" size=20><br />
               notes &nbsp; &nbsp; = <input type="text" name="notes" size=20><br />
               <input type="hidden" name="pk" value="{{ boundingBox.pk }}"><br />
               <input type="submit" value="Submit"><br />
             </form>
           </div>
         </td>
        {% endif %}

      </tr>

     {% endfor %}
    </table>




    <!-- Paginator -->
    {% if boundingBoxes.has_other_pages %}
      <ul class="pagination">
        {% if boundingBoxes.has_previous %}
          <li><a href="?page={{ boundingBoxes.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in boundingBoxes.paginator.page_range %}
          {% if boundingBoxes.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if boundingBoxes.has_next %}
          <li><a href="?page={{ boundingBoxes.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}

  </div>
{% endblock %}